GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwidXNlcklkIjoiNjUwZmUxN2M1MTNhOGNhMjljOGIxNDZkIiwiaWF0IjoxNjk1NTQ0NDY0LCJleHAiOjE2OTU1NDQ0ODR9.2Aqx1Q6Jz1iDy9VvJRNIEeAHDxR_5AfxLHeBvPp1TRs

###
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
    "username" : "hanif ganteng",
    "email" : "hanifganteng@gmail.com",
    "password" : "haniffathan02",
    "confirmPassword" : "haniffathan02"
}

###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "admin123"
}

###
GET http://localhost:5000/api/v1/token

###
DELETE http://localhost:5000/api/v1/logout





###
GET https://cini-kupi-react-js-api.vercel.app/api/v1/users
Authorization: Bearer 
###
# POST https://cini-kupi-react-js-api.vercel.app/api/v1/users
# Content-Type: application/json

# {
#     "username" : "test",
#     "email" : "test@gmail.com",
#     "password" : "test123",
#     "confirmPassword" : "test123"
# }

###
POST https://cini-kupi-react-js-api.vercel.app/api/v1/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "admin123"
}

###
GET https://cini-kupi-react-js-api.vercel.app/api/v1/token